
title: "Please enter a title that specifically describes the qustion here"
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Before posting questions, I hope you check the tutorial and the manual.
        
        * [Tutorial slides](https://khcoder.net/en/tutorial_slides.pdf) and [video](https://www.youtube.com/watch?v=ULhddsc2Nqo)
        * Detailed tutorial: [Part I](http://www.ritsumei.ac.jp/file.jsp?id=325881) & [Part II](http://www.ritsumei.ac.jp/file.jsp?id=346128)
        * [manual](https://khcoder.net/en/manual_en_v3.pdf)

  - type: input
    id: version
    attributes:
      label: "Version number of KH Coder"
      description: "To check the version number, go to \"Help\" \"About\" in the menu of KH Coder."
      placeholder: "e.g. 3.Beta.06, 2.00f, etc."
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: "Your Qeuestion"
      value: |
        **Your Operating System**
        ex. Windows 10, Mac OS X 10.12, Ubuntu 10.14, etc.
        
        **Your Qeuestion**
        A clear and concise description of your question.
        
        **Screenshots**
        If applicable, add screenshots to help explain your question.
        
        **What language of text are you trying to analyze?**
        ex. English, Japanese, Chinese, etc.
    validations:
      required: true

