
title: "Please enter a title that specifically describes the qustion here"
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Before posting questions, I hope you check the tutorial and the manual.
        
        * Tutorial, [slide version](https://khcoder.net/en/tutorial_slides.pdf)
        * Tutorial, Detailed version: [Part I](http://www.ritsumei.ac.jp/file.jsp?id=325881) & [Part II](http://www.ritsumei.ac.jp/file.jsp?id=346128)
        * [manual](https://khcoder.net/en/manual_en_v3.pdf)
  - type: input
    id: version
    attributes:
      label: "KH Coderのバージョン"
      description: "KH Coderのメニューから「ヘルプ」「KH Coderについて」を選択してバージョンをご確認ください。"
      placeholder: "記入例：3.00a, 3.Beta.06など。"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: "ご質問の内容をお書きください"
      description: "すでに入力されているテンプレートを編集しながらご記入ください"
      value: |
        ■お使いのOS
        →記入例：Windows 11, Windows 10, macOS 14, Ubuntu 18.04など
        
        ■スクリーンショット
        可能であれば、質問したい状況をあらわすようなスクリーンショットを添付してください。
        
        ■ご質問の内容
        「うまくいかない」といった書き方ではなく、なるべく多くの情報を含めて、具体的にお書き下さい。
        
        ■チュートリアル・データで試してみると
        操作・分析が上手くいかない場合は、チュートリアルの漱石「こころ」データで同じことを試してみると上手くいくのかどうかをお知らせください。
        
        ■再現用ファイル
        チュートリアル・データなら上手くいくけれど自分のファイルでは上手くいかないという場合、その現象を再現できるファイルをできれば添付してください。
    validations:
      required: true

