
title: "できるだけ具体的に状況をあらわすタイトルをここに入力してください"
labels: ["error", "Non-English"]
body:
  - type: markdown
    attributes:
      value: |
        # 投稿の前に
        
        本掲示板（Discussion）はユーザー同士の助け合いの場です。何に困っているのかを分かりやすく、詳しくお書きいただくほど、応答を得られる可能性が高くなります。
        
        もし確実に応答がほしい場合は、㈱SCREEN アドバンストシステムソリューションズ様ご提供の[「KH Coderサポートパッケージ」](https://www.screen.co.jp/as/solution/khcoder)（Pro Edition以上）を購入することで、 同社のQ & A対応窓口を利用できます。
        
        投稿した問題が解決したら、解決につながったコメントを「answer」としてマークして、Discussionを「close」してください。
        
        # 資料
        
        書き込みしなくても、次の資料にあたることで解決する場合があります。
        
        - [「よくある質問」ページ](https://khcoder.net/FAQ.html)
        - [旧掲示板](http://koichi.nihon.to/cgi-bin/bbs_khn/khcf.cgi)
        - 既存のDiscussion
        - [公式入門書](https://amzn.to/3iyPimF)
        - [詳細マニュアル +alpha](http://amzn.to/2wHFxKg)
        
        # 記入欄
        
  - type: input
    id: version
    attributes:
      label: "KH Coderのバージョン"
      description: "KH Coderのメニューから「ヘルプ」「KH Coderについて」を選択してバージョンをご確認ください。"
      placeholder: "記入例：3.00a, 3.Beta.06など。"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: "お使いのOS"
      placeholder: "記入例：Windows 11, Windows 10, macOS 14, Ubuntu 18.04など"
    validations:
      required: true

  - type: input
    id: path
    attributes:
      label: "KH Coderのインストール先フォルダ（解凍先フォルダ）"
      description: "KH Coder起動時のコンソール画面に「CWD: C:\\khcoder3」のように表示されます。"
      placeholder: "記入例：C:\\khcoder3"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: "どんなエラー・不具合・問題ですか？"
      description: "「うまくいかない」のようなあいまいな書き方ではなく、「○○の結果を期待していたが、□□の結果になった」のように、できるだけ具体的にお書きください。"
      placeholder: "記入例：\n共起ネットワーク作成時に○△□を使おうとするとエラーになる。"
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: "どのように操作すればその問題を再現できますか？"
      placeholder: |
        記入例：
        1. メニューから「ツール」「抽出語」「共起ネットワーク」を選択
        2. 「○△□」にチェックを入れてから「OK」をクリックする
    validations:
      required: true

  - type: textarea
    id: error_messages
    attributes:
      label: "エラー・メッセージ "
      description: "省略や意訳をしていない一字一句そのままのエラーメッセージをお書きください。あるいはエラー画面のスクリーンショットを添付してください。"
    validations:
      required: true

  - type: textarea
    id: console
    attributes:
      label: "コンソール・ウィンドウの表示内容（Macではターミナルの表示内容）"
      render: t
      description: |
        コンソール・ウィンドウの表示内容をすべてここにコピー＆ペーストしてください。長い場合は、内容をテキストファイル・Wordファイル等に保存し、そのファイルを貼り付けていただくのでも結構です。あるいはコンソール・ウィンドウのスクリーンショットを添付していただくのでもOKですが、できれば全内容のコピペの方が、手がかりを得られる可能性が高いです。
        
        Windows 10以前では、タスク・バーのKH Coderアイコンをクリックすれば、コンソール（Console）ウィンドウのアイコンが出てきます。Windows 11ではタスクバーのKH Coderアイコンの近くにコンソール（Console）ウィンドウのアイコンがあるケースが多いです。コンソール・ウィンドウとは黒の背景で，白い文字がずらずらと並んでいるウィンドウです。Windowsでのスクリーンショットの撮り方については、こちらをご覧下さい。
        https://support.hp.com/jp-ja/document/c03715297
        
        なおWindowsでは、KH Coderが起動しない場合はコンソール・ウィンドウも消えてしまって、表示内容を確認できません。この場合には、こちらのページに記載の手順でコンソール・ウィンドウの内容を確認してください。 http://khcoder.net/FAQ.html#vista
        
        Macの場合，エラー発生時のターミナルの表示内容をすべて，コピー＆ペーストでお知らせください。
    validations:
      required: true

  - type: input
    id: kokoro
    attributes:
      label: "その問題はチュートリアルの漱石「こころ」データでも同様に発生しましたか？"
      description: "データに原因があるのか、操作方法に問題があるのか、KH Coderのバグなのかを区別するために、チュートリアル・データでも同じ操作をお試しください。"
      placeholder: "記入例：はい、いいえ、他"
    validations:
      required: true

  - type: textarea
    id: files
    attributes:
      label: "その問題を再現できるファイル（群）"
      description: "その問題を再現できる分析対象ファイル等をなるべく添付してください。必要に応じてZip圧縮して添付してください。チュートリアルとして同梱されているファイルのみで問題を再現可能な場合は不要です。"

  - type: input
    id: language
    attributes:
      label: "分析しようとしているのは何語のテキストですか？"
      placeholder: "記入例：日本語、英語、ロシア語、中国語など"
    validations:
      required: true

  - type: input
    id: filetype
    attributes:
      label: "分析対象として指定しているファイルの形式は何ですか？"
      placeholder: "記入例：テキスト形式（.txt）、Excel形式（.xlsx）、CSV形式（.csv）など"
    validations:
      required: true

  - type: input
    id: virus
    attributes:
      label: "お使いのセキュリティ対策／ウイルス対策ソフトウェア "
      placeholder: "記入例：Norton 360, ウイルスバスター Corp Clientなど"
    validations:
      required: true

  - type: input
    id: cpu
    attributes:
      label: "お使いのCPU"
      description: "不明の場合はPCの機種名をお書きいただいてもOKです。"
      placeholder: "→記入例：Intel Core i5, AMD Ryzen 5, Apple M1, Microsoft SQ2など"
    validations:
      required: true

  - type: markdown
    attributes:
      value: ※ほとんどの入力欄が入力必須となっていますが、どうしても不明なところは「不明」と入力していただいて結構です。
