
title: "短い言葉で具体的に状況をあらわすタイトルをここに入力"
labels: ["error", "Non-English"]
body:
  - type: markdown
    attributes:
      value: |
        本掲示板（Discussion）はユーザー同士の助け合いの場です。何に困っているのかを分かりやすく、詳しくお書きいただくほど、応答を得られる可能性が高くなります。
        
        もし確実に応答がほしい場合は、㈱SCREEN アドバンストシステムソリューションズ様ご提供の[「KH Coderサポートパッケージ」](https://www.screen.co.jp/as/solution/khcoder)（Pro Edition以上）を購入することで、 同社のQ & A対応窓口を利用できます。
        
        書き込みしなくても、次の資料にあたることで解決する場合があります。
        
        - [「よくある質問」ページ](https://khcoder.net/FAQ.html)
        - [旧掲示板](http://koichi.nihon.to/cgi-bin/bbs_khn/khcf.cgi)
        - 既存のDiscussion
        - [公式入門書](https://amzn.to/3iyPimF)
        - [詳細マニュアル +alpha](http://amzn.to/2wHFxKg)
        
  - type: input
    id: version
    attributes:
      label: "KH Coderのバージョン"
      description: "KH Coderのメニューから「ヘルプ」「KH Coderについて」を選択してバージョンをご確認ください。"
      placeholder: "記入例：3.00a, 3.Beta.06など。"
    validations:
      required: true
