title: "短い言葉で具体的に状況をあらわすタイトルをここに入力"
labels: ["error", "Non-English"]
body:
  - type: markdown
    attributes:
      value: |
        本掲示板（Discussion）はユーザー同士の助け合いの場です。何に困っているのかを分かりやすく、詳しくお書きいただくほど、応答を得られる可能性が高くなります。
  - type: input
    id: suggestion
    attributes:
      label: Suggestion
      description: "How might we make this project better?"
      placeholder: "Adding a CODE_OF_CONDUCT.md file would be a great idea."
    validations:
      required: true
