
title: "短い言葉で具体的に状況をあらわすタイトルをここに入力"
labels: ["error", "Non-English"]
body:
  - type: markdown
    attributes:
      value: |
        本掲示板（Discussion）はユーザー同士の助け合いの場です。何に困っているのかを分かりやすく、詳しくお書きいただくほど、応答を得られる可能性が高くなります。
        
        もし確実に応答がほしい場合は、㈱SCREEN アドバンストシステムソリューションズ様ご提供の[「KH Coderサポートパッケージ」](https://www.screen.co.jp/as/solution/khcoder)（Pro Edition以上）を購入することで、 同社のQ & A対応窓口を利用できます。
        
        書き込みしなくても、次の資料にあたることで解決する場合があります。
        
        - [「よくある質問」ページ](https://khcoder.net/FAQ.html)
        - [旧掲示板](http://koichi.nihon.to/cgi-bin/bbs_khn/khcf.cgi)
        - 既存のDiscussion
        - [公式入門書](https://amzn.to/3iyPimF)
        - [詳細マニュアル +alpha](http://amzn.to/2wHFxKg)
        
  - type: input
    id: version
    attributes:
      label: "KH Coderのバージョン"
      description: "KH Coderのメニューから「ヘルプ」「KH Coderについて」を選択してバージョンをご確認ください。"
      placeholder: "記入例：3.00a, 3.Beta.06など。"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: "お使いのOS"
      placeholder: "記入例：Windows 11, Windows 10, macOS 14, Ubuntu 18.04など"
    validations:
      required: true

  - type: input
    id: path
    attributes:
      label: "KH Coderのインストール先フォルダ（解凍先フォルダ）"
      description: "KH Coder起動時のコンソール画面に「CWD: C:\\khcoder3」のように表示されます。"
      placeholder: "記入例：C:\\khcoder3"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: "どんなエラー・不具合・問題ですか？"
      description: "「うまくいかない」のようなあいまいな書き方ではなく、「○○の結果を期待していたが、□□の結果になった」のように、できるだけ具体的にお書きください。"
      placeholder: "記入例：\n共起ネットワーク作成時に○△□を使おうとするとエラーになる。"
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: "どのように操作すればその問題を再現できますか？"
      placeholder: |
        記入例：
        1. メニューから「ツール」「抽出語」「共起ネットワーク」を選択
        2. 「○△□」にチェックを入れてから「OK」をクリックする
    validations:
      required: true

  - type: textarea
    id: error_messages
    attributes:
      label: "エラー・メッセージ "
      description: "省略や意訳をしていない一字一句そのままのエラーメッセージをお書きください。あるいはエラー画面のスクリーンショットを添付してください。"
    validations:
      required: true

  - type: textarea
    id: console
    attributes:
      label: "コンソール・ウィンドウの表示内容（Macではターミナルの表示内容）"
      description: |
        コンソール・ウィンドウの表示内容をすべてここにコピー＆ペーストしてください。長い場合は、内容をテキストファイル・Wordファイル等に保存し、そのファイルを貼り付けていただくのでも結構です。あるいはコンソール・ウィンドウのスクリーンショットを添付していただくのでもOKですが、できれば全内容のコピペの方が、手がかりを得られる可能性が高いです。
        
        Windows 10以前では、タスク・バーのKH Coderアイコンをクリックすれば、コンソール（Console）ウィンドウのアイコンが出てきます。Windows 11ではタスクバーのKH Coderアイコンの近くにコンソール（Console）ウィンドウのアイコンがあるケースが多いです。コンソール・ウィンドウとは黒の背景で，白い文字がずらずらと並んでいるウィンドウです。Windowsでのスクリーンショットの撮り方については、こちらをご覧下さい。
        https://support.hp.com/jp-ja/document/c03715297
        
        なおWindowsでは、KH Coderが起動しない場合はコンソール・ウィンドウも消えてしまって、表示内容を確認できません。この場合には、こちらのページに記載の手順でコンソール・ウィンドウの内容を確認してください。 http://khcoder.net/FAQ.html#vista
        
        Macの場合，エラー発生時のターミナルの表示内容をすべて，コピー＆ペーストでお知らせください。
    validations:
      required: true

  - type: dropdown
    id: kokoro
    attributes:
      label: "その問題はチュートリアルの漱石「こころ」データでも同様に発生しましたか？"
      options:
        - "はい"
        - "いいえ"
    validations:
      required: true
